basePath: /api/v1
definitions:
  main.MessageRequest:
    description: The message request body
    properties:
      message:
        type: string
      number:
        type: string
    type: object
info:
  contact: {}
  description: Basic Auth
  title: Basic Auth
paths:
  /recvMessage:
    get:
      consumes:
      - application/json
      description: Receive a message with the specified number
      parameters:
      - description: The number parameter
        in: query
        name: number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BasicAuth: []
      summary: Receive message
  /sendMessage:
    post:
      consumes:
      - application/json
      description: send message
      parameters:
      - description: Input message and number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.MessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BasicAuth: []
      summary: send message
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
